name: run-python-script

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install github-action-utils requests

    - name: Run Python Script
      shell: python
      id: out
      run: |
        import github_action_utils as gha_utils
        import requests
        
        data = requests.get("https://raw.githubusercontent.com/saadmk11/github-action-utils/main/CHANGELOG.md")

        with gha_utils.group("My Group"):
            gha_utils.error(
                "Error message", title="Error Title", file="example.py",
                col=1, end_column=2, line=1, end_line=2,
            )
            gha_utils.notice("Another notice message")
            gha_utils.append_job_summary(data.text)
            gha_utils.set_output("out", data.text)

    - name: Output
      run: |
        echo "${{ steps.out.outputs.data }}"
        echo "${{ steps.out.outputs.data }}" >> $GITHUB_STEP_SUMMARY
